=== victorsoares96/eslint-plugin-react-intl-universal/src/rules/no-literal-string/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"mode": {
			"type": "string",
			"enum": ["jsx-text-only", "jsx-only", "all"]
		},
		"jsx-components": {
			"type": "object",
			"properties": {
				"include": { "type": "array", "items": { "type": "string" } },
				"exclude": {
					"type": "array",
					"items": { "type": "string" }
				}
			}
		},
		"jsx-attributes": {
			"type": "object",
			"properties": {
				"include": { "type": "array", "items": { "type": "string" } },
				"exclude": {
					"type": "array",
					"items": { "type": "string" }
				}
			}
		},
		"words": {
			"type": "object",
			"properties": {
				"exclude": {
					"type": "array",
					"items": { "type": "string" }
				}
			}
		},
		"callees": {
			"type": "object",
			"properties": {
				"include": { "type": "array", "items": { "type": "string" } },
				"exclude": {
					"type": "array",
					"items": { "type": "string" }
				}
			}
		},
		"object-properties": {
			"type": "object",
			"properties": {
				"include": { "type": "array", "items": { "type": "string" } },
				"exclude": { "type": "array", "items": { "type": "string" } }
			}
		},
		"class-properties": {
			"type": "object",
			"properties": {
				"include": { "type": "array", "items": { "type": "string" } },
				"exclude": {
					"type": "array",
					"items": { "type": "string" }
				}
			}
		},
		"message": { "type": "string" },
		"should-validate-template": { "type": "boolean" }
	}
}

=== victorsoares96/eslint-plugin-react-intl-universal/src/rules/no-literal-string/default.json
{
	"mode": "jsx-text-only",
	"jsx-components": {
		"include": [],
		"exclude": ["Trans"]
	},
	"jsx-attributes": {
		"include": [],
		"exclude": ["className", "styleName", "style", "type", "key", "id", "width", "height"]
	},
	"words": {
		"exclude": ["[0-9!-/:-@[-`{-~]+", "[A-Z_-]+"]
	},
	"callees": {
		"exclude": [
			"intl(ext)?",
			"get",
			"set",
			"put",
			"post",
			"delete",
			"patch",
			"append",
			"getHTML",
			"determineLocale",
			"formateHTMLMessage",
			"formatMessage",
			"getInitOptions",
			"init",
			"load",
			"describe",
			"it",
			"push",
			"require",
			"addEventListener",
			"removeEventListener",
			"postMessage",
			"getElementById",
			"dispatch",
			"commit",
			"includes",
			"indexOf",
			"endsWith",
			"startsWith",
			"on",
			"emit"
		]
	},
	"object-properties": {
		"include": [],
		"exclude": ["[A-Z][a-z]+", "^#[0-9a-f]{3,6}$"]
	},
	"class-properties": {
		"include": [],
		"exclude": ["displayName"]
	},
	"message": "disallow literal string",
	"should-validate-template": true
}
